version: "3"

tasks:
  build:
    desc: builds white-noise
    cmds:
      - mkdir -p ./bin
      - go build -o ./bin/white-noise cmd/main.go
  run:
    desc: runs white-noise
    deps: [build]
    cmds:
      - ./bin/white-noise
  install:
    desc: installs white-noise
    deps: [build]
    cmds:
      - cp bin/white-noise "$(go env GOPATH)/bin/"